name: github-actions-lab
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            guilhermefaleiros/github-actions-lab:${{ github.run_number }}
            guilhermefaleiros/github-actions-lab:latest
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect to Kubernetes
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: do-nyc1-k8s-lab
